import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";
// @ts-ignore — circomlibjs ships no types for poseidonContract
import { poseidonContract } from "circomlibjs";

/**
 * Deploy the Poseidon(2) hasher from circomlib's generated bytecode.
 *
 * Its output is bit-for-bit identical to the Poseidon used inside the Circom
 * circuits, so on-chain Merkle roots match the proofs agents generate. Deployed
 * once and shared by every lottery (referenced via the factory).
 */
const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployments, getNamedAccounts } = hre;
  const { deployer } = await getNamedAccounts();

  const abi = poseidonContract.generateABI(2);
  const bytecode = poseidonContract.createCode(2);

  await deployments.deploy("PoseidonT3", {
    from: deployer,
    contract: { abi, bytecode },
    log: true,
    waitConfirmations: hre.network.name === "hardhat" ? 0 : 3,
  });
};

func.tags = ["Poseidon"];
export default func;
